// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_NbT-zJ572-SHdE7t6pDAd2EOwJ2zMes',
    appId: '1:983597733024:web:4516180dc78ecbd3aaa5c5',
    messagingSenderId: '983597733024',
    projectId: 'petwell-24602',
    authDomain: 'petwell-24602.firebaseapp.com',
    databaseURL: 'https://petwell-24602-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petwell-24602.firebasestorage.app',
    measurementId: 'G-LYT2RGGGNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxdjCuEIrtNXerJjqxWybzIhX2ahLQQ8Y',
    appId: '1:983597733024:android:a338197f52869c51aaa5c5',
    messagingSenderId: '983597733024',
    projectId: 'petwell-24602',
    databaseURL: 'https://petwell-24602-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petwell-24602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7WNZ_SrwyblYKebpwcTHwCjij_Rg8E7E',
    appId: '1:983597733024:ios:91680d07edf6c50aaaa5c5',
    messagingSenderId: '983597733024',
    projectId: 'petwell-24602',
    databaseURL: 'https://petwell-24602-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petwell-24602.firebasestorage.app',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7WNZ_SrwyblYKebpwcTHwCjij_Rg8E7E',
    appId: '1:983597733024:ios:91680d07edf6c50aaaa5c5',
    messagingSenderId: '983597733024',
    projectId: 'petwell-24602',
    databaseURL: 'https://petwell-24602-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petwell-24602.firebasestorage.app',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_NbT-zJ572-SHdE7t6pDAd2EOwJ2zMes',
    appId: '1:983597733024:web:98d14d4f900c8df2aaa5c5',
    messagingSenderId: '983597733024',
    projectId: 'petwell-24602',
    authDomain: 'petwell-24602.firebaseapp.com',
    databaseURL: 'https://petwell-24602-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petwell-24602.firebasestorage.app',
    measurementId: 'G-TCNQPPHL88',
  );
}
